import { gsap } from '../core/gsap-config.js';
import { MOTION } from '../config/motion-tokens.js';

export const initNavbarMotion = () => {
    const navbar = document.querySelector('.navbar');
    const toggle = document.querySelector('.navbar-toggle');
    const closeBtn = document.querySelector('.nav-close');
    const overlay = document.querySelector('.nav-overlay');
    const links = document.querySelectorAll('.navbar-links li');
    
    if (!navbar) return;

    // 1. Initial Load Reveal (Desktop & Mobile header)
    // Usamos from() para que el CSS nativo dicte el estado visible final
    gsap.from(navbar, {
        y: '-100%',
        autoAlpha: 0,
        duration: MOTION.duration.cinematic,
        ease: MOTION.easing.menu,
        clearProps: "all" // Elimina transform y autoAlpha al terminar para no corromper el layout responsive
    });

    // 2. Scroll logic (Vanilla is fine here, GSAP for state)
    window.addEventListener('scroll', () => {
        if (window.scrollY > 50) navbar.classList.add('scrolled');
        else navbar.classList.remove('scrolled');
    });

    // 3. Premium Mobile Menu Logic
    if (toggle && overlay) {
        let menuTl = null;

        const initMenuTimeline = () => {
            if (menuTl) return menuTl;
            
            menuTl = gsap.timeline({ paused: true, reversed: true });
            menuTl
                .to(overlay, { 
                    autoAlpha: 1, // handles opacity and visibility
                    duration: MOTION.duration.standard,
                    ease: "power2.inOut" 
                })
                .to('.navbar-nav', {
                    x: '0%',
                    duration: MOTION.duration.medium,
                    ease: MOTION.easing.menu
                }, "<") // Start at the same time as overlay
                .fromTo(links, 
                    { opacity: 0, x: 20 },
                    { 
                        opacity: 1, 
                        x: 0, 
                        stagger: MOTION.stagger.standard, 
                        duration: MOTION.duration.standard,
                        ease: "power2.out"
                    }, 
                    "-=0.4"
                );
            return menuTl;
        };

        const toggleMenu = () => {
            const tl = initMenuTimeline();
            const isReversed = tl.reversed();
            toggle.classList.toggle('active');
            toggle.setAttribute('aria-expanded', isReversed);
            document.body.classList.toggle('no-scroll', isReversed); // Body lock
            
            if (isReversed) {
                navbar.classList.add('open');
                tl.play();
            } else {
                tl.reverse().then(() => {
                    navbar.classList.remove('open');
                });
            }
        };

        toggle.addEventListener('click', toggleMenu);
        
        if (closeBtn) {
            closeBtn.addEventListener('click', () => {
                const tl = initMenuTimeline();
                if (!tl.reversed()) toggleMenu();
            });
        }
        
        overlay.addEventListener('click', () => {
            const tl = initMenuTimeline();
            if (!tl.reversed()) toggleMenu();
        });

        // Close on link click
        document.querySelectorAll('.navbar-links a').forEach(link => {
            link.addEventListener('click', () => {
                const tl = initMenuTimeline();
                if (!tl.reversed()) toggleMenu();
            });
        });

        // Handle resize cleanup to avoid leftover inline styles from breaking responsive layout
        window.addEventListener('resize', () => {
            if (window.innerWidth >= 768) {
                navbar.classList.remove('open');
                toggle.classList.remove('active');
                toggle.setAttribute('aria-expanded', 'false');
                document.body.classList.remove('no-scroll');
                
                if (menuTl) {
                    menuTl.progress(0).pause();
                }
                // Clear any inline styles generated by GSAP
                gsap.set([overlay, '.navbar-nav', links], { clearProps: "all" });
            }
        });
    }
};
